title: Unnamed Home
email: ntl@riseup.net
description: Blog about nearly everything that comes to my mind.
baseurl: ""
url: ""

github_username: rilysh
permalink: /:year/:month/:day/:title:output_ext

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num.html'
  title: ':title - page :num'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
  tags:
    title: 'Posts tagged with :tag'
  collections:

logo: assets/void.png
markdown: kramdown
sass:
  style: compressed
